export const APP_WRITE_ID = 'nuxt-shop02'
export const DB_ID = 'shop-base'
export const COLLECTION_MAN = 'man-shoes'
export const COLLECTION_WOMEN = 'women-shoes'
export const COLLECTION_CART = 'cart'
export const COLLECTION_FAVORITES = 'favorites'
export const STORAGE_ID = 'storage'